apiVersion: v1
kind: Service
metadata:
  name: jimc-simple-autos-lb
spec:
  selector:
    type: LoadBalancer
    app: jimc-simple-autos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
